---
- hosts: nodes
  gather_facts: no
  tasks:
  - name: Copy prepare script
    copy: src=./prepare-node.sh dest=/root
  - name: Change mode
    file: path=/root/prepare-node.sh mode=u+x
  - name: Prepare
    command: /root/prepare-node.sh
- hosts: puppetmaster
  gather_facts: no
  tasks:
  - name:
    shell: puppet cert sign mysql.test.localdomain review.test.localdomain zuul.test.localdomain zm.test.localdomain jenkins.test.localdomain 
- hosts: nodes
  gather_facts: no
  tasks:
  - name:
    shell: puppet agent --enable 
